version: '3.9'
services:
  web:
    build: 
      dockerfile: ./app/Dockerfile
      context: .
    container_name: web
    # restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=mirea
      - POSTGRES_HOST=postgress
      - POSTGRES_PORT=5437
    ports:
      - "8000:8000"


  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mirea
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
